---
galaxy_info:
  author: Joe Gordon
  description: Set up weechat with registered freenode account.
  license: BSD
  min_ansible_version: 1.2
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - wheezy
dependencies: []
