---
- name: upgrade packages
  apt: update_cache=yes upgrade=dist
  sudo: yes
  when: upgrade
- name: Install tools
  apt: name={{item}} state=present
  sudo: yes
  with_items:
    - git
    - vim
    - mosh
    - tmux

- name: Add .vimrc
  # don't copy if already a .vimrc
  copy: src=vimrc dest=~/.vimrc force=no

- name: set up aliases
  lineinfile: dest=~/.bashrc line='{{item}}'
  with_items:
   - alias rm="rm -i"
   - alias v="vim"
   - alias g="git"
